(() => {
  const ns = window.ImageGen = window.ImageGen || {};
  const $ = (selector) => document.querySelector(selector);

  ns.els = {
    loginPanel: $('#loginPanel'), emailInput: $('#emailInput'), loginBtn: $('#loginBtn'), loginStatus: $('#loginStatus'),
    userBar: $('#userBar'), currentUserEmail: $('#currentUserEmail'), currentUserBalance: $('#currentUserBalance'), adminToggleBtn: $('#adminToggleBtn'), logoutBtn: $('#logoutBtn'),
    appShell: $('#appShell'), adminPanel: $('#adminPanel'), adminRefreshBtn: $('#adminRefreshBtn'), adminAddEmail: $('#adminAddEmail'), adminAddName: $('#adminAddName'), adminAddBalance: $('#adminAddBalance'), adminAddUserBtn: $('#adminAddUserBtn'), adminStatus: $('#adminStatus'), adminUsersBody: $('#adminUsersBody'), adminLogsBody: $('#adminLogsBody'),
    refreshMyLogsBtn: $('#refreshMyLogsBtn'), myLogsList: $('#myLogsList'), historySearchInput: $('#historySearchInput'), historyFilterSelect: $('#historyFilterSelect'), model: $('#model'), modelNote: $('#modelNote'), prompt: $('#prompt'), promptStats: $('#promptStats'), aspectRatio: $('#aspectRatio'), resolution: $('#resolution'), imageCount: $('#imageCount'), officialSettings: $('#officialSettings'), quality: $('#quality'), outputFormat: $('#outputFormat'), compressionField: $('#compressionField'), outputCompression: $('#outputCompression'), compressionValue: $('#compressionValue'), priceTotal: $('#priceTotal'), priceDetail: $('#priceDetail'), priceBalanceText: $('#priceBalanceText'), priceWarning: $('#priceWarning'), advancedSettings: $('#advancedSettings'), advancedSummary: $('#advancedSummary'), runBtn: $('#runBtn'), clearBtn: $('#clearBtn'), status: $('#status'), progressPanel: $('#progressPanel'), progressHint: $('#progressHint'), progressPercent: $('#progressPercent'), progressTrack: $('#progressTrack'), progressBar: $('#progressBar'), progressElapsed: $('#progressElapsed'), generationSteps: $('#generationSteps'), resultSummary: $('#resultSummary'), notifyToggle: $('#notifyToggle'), notifyToggleField: $('#notifyToggleField'), resultLive: $('#resultLive'), emptyState: $('#emptyState'), resultCard: $('#resultCard'), resultGrid: $('#resultGrid'), resultActions: $('#resultActions'), refreshCurrentTaskBtn: $('#refreshCurrentTaskBtn'), reuseResultPromptBtn: $('#reuseResultPromptBtn'), regenerateResultBtn: $('#regenerateResultBtn'), useAllResultsAsReferenceBtn: $('#useAllResultsAsReferenceBtn'), downloadResultZipBtn: $('#downloadResultZipBtn'), taskIdText: $('#taskIdText'), debugDetails: $('#debugDetails'), debugOutput: $('#debugOutput'),
    referenceFileInput: $('#referenceFileInput'), referenceUploadBtn: $('#referenceUploadBtn'), clearReferencesBtn: $('#clearReferencesBtn'), referenceCount: $('#referenceCount'), referencePreviewGrid: $('#referencePreviewGrid'), referenceStatus: $('#referenceStatus'),
    editUploadInput: $('#editUploadInput'), editUploadBtn: $('#editUploadBtn'), editEmptyState: $('#editEmptyState'), editEmptyStatus: $('#editEmptyStatus'), editWorkspace: $('#editWorkspace'), editChangeImageBtn: $('#editChangeImageBtn'), editToolGroup: $('#editToolGroup'), editColorGroup: $('#editColorGroup'), editWidthGroup: $('#editWidthGroup'), editUndoBtn: $('#editUndoBtn'), editClearBtn: $('#editClearBtn'), editCanvasStage: $('#editCanvasStage'), editBaseCanvas: $('#editBaseCanvas'), editAnnotationCanvas: $('#editAnnotationCanvas'), editSourceNote: $('#editSourceNote'), editModel: $('#editModel'), editAspectRatio: $('#editAspectRatio'), editResolution: $('#editResolution'), editParamsNote: $('#editParamsNote'), editPrompt: $('#editPrompt'), editPromptStats: $('#editPromptStats'), editAppendToggle: $('#editAppendToggle'), editAnnotationText: $('#editAnnotationText'), editSubmitBtn: $('#editSubmitBtn'), editStatus: $('#editStatus')
  };
})();
